//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thunderdome {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExtensionRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtensionRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thunderdome.ExtensionRes", typeof(ExtensionRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _000210_computer_add {
            get {
                object obj = ResourceManager.GetObject("_000210_computer_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _000260_computer_export {
            get {
                object obj = ResourceManager.GetObject("_000260_computer_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _000275_computer_save {
            get {
                object obj = ResourceManager.GetObject("_000275_computer_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _000276_computer_settings {
            get {
                object obj = ResourceManager.GetObject("_000276_computer_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _000410_folder_add {
            get {
                object obj = ResourceManager.GetObject("_000410_folder_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _000440_folder_search {
            get {
                object obj = ResourceManager.GetObject("_000440_folder_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Standard Customizations.
        /// </summary>
        internal static string Category_DataStandardCustomizations {
            get {
                return ResourceManager.GetString("Category_DataStandardCustomizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault Folders.
        /// </summary>
        internal static string Category_VaultFoldersCustomizations {
            get {
                return ResourceManager.GetString("Category_VaultFoldersCustomizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Files.
        /// </summary>
        internal static string ConfigFilesController_ConfigurationFiles {
            get {
                return ResourceManager.GetString("ConfigFilesController_ConfigurationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Configuration.
        /// </summary>
        internal static string ConfigFilesController_FilterConfiguration {
            get {
                return ResourceManager.GetString("ConfigFilesController_FilterConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Configuration.
        /// </summary>
        internal static string ConfigFilesController_GrdiConfiguration {
            get {
                return ResourceManager.GetString("ConfigFilesController_GrdiConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid State.
        /// </summary>
        internal static string ConfigFilesController_GridState {
            get {
                return ResourceManager.GetString("ConfigFilesController_GridState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        internal static string ConfigFilesController_Shortcuts {
            get {
                return ResourceManager.GetString("ConfigFilesController_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Styles.
        /// </summary>
        internal static string ConfigFilesController_ViewStyles {
            get {
                return ResourceManager.GetString("ConfigFilesController_ViewStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Folders.
        /// </summary>
        internal static string ConfigFilesController_WorkingFolders {
            get {
                return ResourceManager.GetString("ConfigFilesController_WorkingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (localization strings).
        /// </summary>
        internal static string DataStandardController_0_LocalizationStrings {
            get {
                return ResourceManager.GetString("DataStandardController_0_LocalizationStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD.
        /// </summary>
        internal static string DataStandardController_CAD {
            get {
                return ResourceManager.GetString("DataStandardController_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD.Custom.
        /// </summary>
        internal static string DataStandardController_CAD_Custom {
            get {
                return ResourceManager.GetString("DataStandardController_CAD_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpFiles.
        /// </summary>
        internal static string DataStandardController_HelpFiles {
            get {
                return ResourceManager.GetString("DataStandardController_HelpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault.
        /// </summary>
        internal static string DataStandardController_Vault {
            get {
                return ResourceManager.GetString("DataStandardController_Vault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault.Custom.
        /// </summary>
        internal static string DataStandardController_Vault_Custom {
            get {
                return ResourceManager.GetString("DataStandardController_Vault_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deco File: {0}.
        /// </summary>
        internal static string DecoController_DecoFile_0 {
            get {
                return ResourceManager.GetString("DecoController_DecoFile_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECO Files.
        /// </summary>
        internal static string DecoController_DecoFiles {
            get {
                return ResourceManager.GetString("DecoController_DecoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECO settings.
        /// </summary>
        internal static string DecoController_DecoSettings {
            get {
                return ResourceManager.GetString("DecoController_DecoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to collect info for deployment package.
        /// </summary>
        internal static string DeploymentContainerExceptionMessage {
            get {
                return ResourceManager.GetString("DeploymentContainerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug-ins.
        /// </summary>
        internal static string ExtensionsController_PlugIns {
            get {
                return ResourceManager.GetString("ExtensionsController_PlugIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to configure file moving operations.
        /// </summary>
        internal static string MoveOperationsExceptionMessage {
            get {
                return ResourceManager.GetString("MoveOperationsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Search: {0}.
        /// </summary>
        internal static string SavedSearchesController_SavedSearch_0 {
            get {
                return ResourceManager.GetString("SavedSearchesController_SavedSearch_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Searches.
        /// </summary>
        internal static string SavedSearchesController_SavedSearches {
            get {
                return ResourceManager.GetString("SavedSearchesController_SavedSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Groups.
        /// </summary>
        internal static string SavedSearchesController_SavedSearchesGroups {
            get {
                return ResourceManager.GetString("SavedSearchesController_SavedSearchesGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Vault User Settings.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_Backup_BackupVaultUserSettings {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_Backup_BackupVaultUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Vault product.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_Backup_ErrorUnknownVaultProduct {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_Backup_ErrorUnknownVaultProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create backup: {0}.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_BackupCmdExecute_UnableToCreateBackup_0 {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_BackupCmdExecute_UnableToCreateBackup_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed..
        /// </summary>
        internal static string ThunderdomeExplorerExtension_BackupCompleted {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_BackupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} does not exist.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_BackupFolder_0_DoesNotExist {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_BackupFolder_0_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Vault Settings.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_BackupVaultSettings {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_BackupVaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup your Vault settings.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_CommandSites_BackupCommand {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_CommandSites_BackupCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decide which components to push to Vault users.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_CommandSites_ConfigureationCommandDescription {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_CommandSites_ConfigureationCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select deployments to apply on your PC.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_CommandSites_DeployCommandDescription {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_CommandSites_DeployCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Deployments....
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureationCommand {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Created.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureThunderdome_DeploymentCreated {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureThunderdome_DeploymentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is already used..
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureThunderdome_DeploymentNameUsed {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureThunderdome_DeploymentNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{newDeploymentName}&apos; is already used as the default deployment name..
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureThunderdome_DeploymentNameUsedForDefault {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureThunderdome_DeploymentNameUsedForDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid deployment folder.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureThunderdome_InvalidDeploymentFolderDefined {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureThunderdome_InvalidDeploymentFolderDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deployment name is invalid.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureThunderdome_InvalidDeploymentNmae {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureThunderdome_InvalidDeploymentNmae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for the deployment Folde.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureThunderdome_NoDeploymentFolderDefined {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureThunderdome_NoDeploymentFolderDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder selected..
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureThunderdome_NoFolderSelected {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureThunderdome_NoFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Configuration Administrators can use this function.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureThunderdome_OnlyAdminCanUseThisFunction {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureThunderdome_OnlyAdminCanUseThisFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a pending deployment. Please close Vault Client..
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ConfigureThunderdome_PendingDeployment {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ConfigureThunderdome_PendingDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply the deployment:  {0}.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_DeployCmdExecute_UnableToDeploy_0 {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_DeployCmdExecute_UnableToDeploy_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy....
        /// </summary>
        internal static string ThunderdomeExplorerExtension_DeployCommand {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_DeployCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit required.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_DisplayResultMessage_ExitRequired {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_DisplayResultMessage_ExitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following configurations have not been set up properly and will not be fully applied: .
        /// </summary>
        internal static string ThunderdomeExplorerExtension_DisplayResultMessage_FollowingConfigurationsFailedToSetup {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_DisplayResultMessage_FollowingConfigurationsFailedTo" +
                        "Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates downloaded. 
        ///You need exit the Vault client to complete the update process.
        ///The Vault Client will restart when the update is complete..
        /// </summary>
        internal static string ThunderdomeExplorerExtension_DisplayResultMessage_UpdatesDownloaded {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_DisplayResultMessage_UpdatesDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the content of the active deployment with the latest file version ?.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_ForceDeploymentUpdate {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_ForceDeploymentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped Folder &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string ThunderdomeExplorerExtension_MappedFolderNotExist {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_MappedFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderdome.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_MessageBoxCaption {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_MessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderdome could not successfully execute configuration update..
        /// </summary>
        internal static string ThunderdomeExplorerExtension_OnLogOn_ThunderdomeCouldNotUpdate {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_OnLogOn_ThunderdomeCouldNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderdome could not trigger configuration deployment. Try starting deploy.exe manually..
        /// </summary>
        internal static string ThunderdomeExplorerExtension_OnShutdow_CouldNotTriggerDeployment {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_OnShutdow_CouldNotTriggerDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These custom deployments have recently been updated on the server. Please apply these deployments manually on your computer:.
        /// </summary>
        internal static string ThunderdomeExplorerExtension_PopUpCustomDeploymentUpdatesAvailable {
            get {
                return ResourceManager.GetString("ThunderdomeExplorerExtension_PopUpCustomDeploymentUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderdome deployment.
        /// </summary>
        internal static string VaultUtil_ThunderdomeDeployment {
            get {
                return ResourceManager.GetString("VaultUtil_ThunderdomeDeployment", resourceCulture);
            }
        }
    }
}
